[package]
name = "sh2hvnknf"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[profile.release]
strip = true
lto = true
panic = "abort"

[dependencies]
anyhow = "1.0.95"
log = "0.4.25"
memchr = "2.7.4"
nalgebra = "0.33.2"
simplelog = "0.12.2"
toml = "0.8.19"
windows = { version = "0.59.0", features = ["Win32_Foundation", "Win32_System_Memory", "Win32_System_ProcessStatus", "Win32_System_SystemServices", "Win32_System_Threading", "Win32_UI_Input", "Win32_UI_Input_KeyboardAndMouse"] }